name: Build Action

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.JS 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm test
      - name: Create Pull Request
        if: >
          matrix.os == 'ubuntu-latest' &&
          (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/releases/'))
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dist"
          branch: update-dist-${{ github.ref_name }}
          title: "chore: update dist"
          body: "Automated update of dist/ after build"
          base: ${{ github.ref_name }}
          add-paths: dist/